{% set name = "powerlaw" %}
{% set version = "2.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "bf4e030a93940c02ad4b0bd449cbe131fcaf3d95767891d84f89c4d7c8d138b0"

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - matplotlib-base
    - mpmath
    - numpy
    - python >={{ python_min }}
    - scipy
test:
  requires:
    - python {{ python_min }}
  imports:
    - powerlaw

about:
  home: "http://www.github.com/jeffalstott/powerlaw"
  license: "MIT"
  license_family: "MIT"
  license_file: "powerlaw.py"
  summary: "Toolbox for testing if a probability distribution fits a power law"


extra:
  recipe-maintainers:
    - jaidevjoshi83
